[package]
name = "crabcakes"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5.48", features = ["derive", "env"] }
http-body-util = "0.1.3"
hyper = { version = "1.7.0", features = ["http1", "http2", "server"] }
hyper-util = { version = "0.1.17", features = [
    "tokio",
    "http1",
    "http2",
    "server",
] }
mime_guess = "2.0"
quick-xml = { version = "0.36", features = ["serialize"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }

[dev-dependencies]
aws-config = "1.5"
aws-sdk-s3 = "1.52"
reqwest = "0.12"
tempfile = "3.0"
tokio-test = "0.4"
