[package]
name = "crabcakes"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5.48", features = ["derive", "env"] }
http = "1.3.1"
http-body-util = "0.1.3"
hyper = { version = "1.7.0", features = ["http1", "http2", "server"] }
hyper-util = { version = "0.1.17", features = [
    "tokio",
    "http1",
    "http2",
    "server",
] }
# iam-rs = "0.0.23"
iam-rs = { path = "../iam-rs" }
mime_guess = "2.0"
quick-xml = { version = "0.38.3", features = ["serialize"] }
scratchstack-aws-principal = "0.4.9"
scratchstack-aws-signature = "0.11.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.145"
sha2 = "0.10.9"
tempfile = "3.23"
tokio = { version = "1.47.1", features = ["full"] }
tower = "0.5.2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
aws-config = "1.8"
aws-sdk-s3 = "1.106"
reqwest = "0.12"
tempfile = "3.23"
tokio-test = "0.4"
